
<!DOCTYPE HTML>

<html>
    <head>

    </head>
    <body>
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper">Employee Registration Form</span>    
    </h1>
        <div class="row">
            <div class="col-md-8">
                <form name="addData" method="post" id="addData" class="form"
                    action="<?php echo $block->getBaseURl().'login/index/save';  ?>"
                    data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                    data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <fieldset class="fieldset row">

            <div class="fields col-md-6">
                <div class="field name required">
                    <label class="label" for="title"><span><?= $block->
                           escapeHtmlAttr(__('Employee ID')) ?></span></label>
                <div class="control">
                    <input name="employeeid" id="employeeid" title="Employee ID" value="" class="input-text" type="text"
                           data-validate="{required:true}">
                </div>
            </div>


            <div class="field name required">
                <label class="label" for="title"><span><?= $block->
                       escapeHtmlAttr(__('First Name')) ?></span></label>
                <div class="control">
                    <input name="firstname" id="firstname" title="Employee First Name" value="" class="input-text" type="text"
                           data-validate="{required:true, 'validate-alpha-with-spaces':true}">
                </div>
            </div>


            <div class="field name required">
                <label class="label" for="title"><span><?= $block->
                       escapeHtmlAttr(__('Last Name')) ?></span></label>
                <div class="control">
                    <input name="lastname" id="lastname" title="Employee Last Name" value="" class="input-text" type="text"
                           data-validate="{required:true, 'validate-alpha-with-spaces':true}">
                </div>
            </div>


            <div class="field name required">
                <label class="label" for="title"><span><?= $block->
                       escapeHtmlAttr(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="Email" value="" class="input-text" type="text"
                           data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>


            <div class="field name required">
                <label class="label" for="title"><span><?= $block->
                       escapeHtmlAttr(__('Mobile Number')) ?></span></label>
                <div class="control">
                    <input name="mobilenumber" id="mobilenumber" title="Mobile Number" value="" class="input-text"
                           type="number" data-validate="{required:true, 'validate-number':true}">
                </div>
            </div>


            <div class="field name required">
                <label class="label" for="title"><span><?= $block->
                       escapeHtmlAttr(__('Company Name')) ?></span></label>
                <div class="control">
                    <input name="companyname" id="companyname" title="Company Name" value="" class="input-text" type="text"
                           data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                </div>
            </div>


            <div class="field name required">
                <label class="label" for="title"><span><?= $block->
                       escapeHtmlAttr(__('Department')) ?></span></label>
                <div class="control">
                    <input name="department" id="department" title="Department" value="" class="input-text" type="text"
                           data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                </div>
            </div>


            <div class="field name required">
                <label class="label" for="title"><span><?= $block->
                       escapeHtmlAttr(__('Occupation')) ?></span></label>
                <div class="control">
                    <input name="occupation" id="occupation" title="Occupation" value="" class="input-text" type="text"
                           data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                </div>
            </div>


            <div class="field name required">
                <label class="label" for="title"><span><?= $block->
                       escapeHtmlAttr(__('Address')) ?></span></label>
                <div class="control">
                    <textarea name="address" id="address" title="Address" value="" class="input-text" type="textarea"
                              data-validate="{required:true, 'validate-alphanum-with-spaces':true}"> </textarea>
                </div>
            </div>


            <div class="field name required">
                <label class="label" for="title"><span><?= $block->
                       escapeHtmlAttr(__('Joining Date')) ?></span></label>
                <div class="control">
                    <input name="joiningdate" id="joiningdate" title="Joining Date" value="" class="input-text" type="date"
                           data-validate="{required:true}">
                </div>
            </div>


            <div class="field name required">
                <label class="label" for="title"><span><?= $block->
                       escapeHtmlAttr(__('DOB')) ?></span></label>
                <div class="control">
                    <input name="dob" id="dob" title="DOB" value="" class="input-text" type="date"
                           data-validate="{required:true}">
                </div>
            </div>
        </div>

    </fieldset>
</fieldset>



        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                        escapeHtmlAttr(__('Save')) ?></span></button>
            </div>
        </div>

    </form>

        </div>
    </div>

</body>

    <footer>

    </footer>

</html>
